---
- hosts: all
  become: true
  tasks:
    - name: update apt packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: upgrade apt packages
      apt:
        upgrade: full

    - name: clean & remove apt packages
      apt:
        autoclean: yes
        autoremove: yes
    
    - name: disable swap
      command: swapoff -a  
