---
- hosts: all
  become: true
  tasks:
    - name: Add multiverse repository
      ansible.builtin.apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu/ focal multiverse
        state: present
    
    - name: Add 32-bit architecture
      command: dpkg --add-architecture i386

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install steamcmd
      shell: |
        echo steam steam/question select "I AGREE" | debconf-set-selections && \
        echo steam steam/license note '' | debconf-set-selections && \
        DEBIAN_FRONTEND=noninteractive apt-get install -q -y --no-install-recommends \
          lib32gcc1 steamcmd && \
        ln -sf /usr/games/steamcmd /usr/bin/steamcmd
    
    - name: Install dedicated server
      shell: steamcmd +force_install_dir /home/vagrant/SatisfactoryDedicatedServer +login anonymous +app_update 1690800 -beta public validate +quit
      become_user: vagrant

    - name: Create systemd service
      template: src=files/satisfactory.service dest=/etc/systemd/system/satisfactory.service

    - name: Reload systemctl daemon
      command: systemctl daemon-reload

    - name: Enable service
      command: systemctl enable satisfactory

    - name: Start service
      command: systemctl start satisfactory

    - name: Fetch service status
      command: systemctl status satisfactory
      register: service_status
    
    - name: Print service status
      ansible.builtin.debug:
        var: service_status
